# paths for rust if it's lazily installed
export PATH=$PATH:$HOME/.cargo/bin

# paths for python if it's lazily installed
export PATH=$PATH:$HOME/.local/bin

# paths
export PATH=$PATH:$HOME/devel/devenv/lazybin
