# path for go if it's lazily installed
export PATH=$PATH:$LOCAL_BIN/go/bin
export GOBIN=$LOCAL_BIN

# path for ruby if it's lazily installed
export GEM_HOME=$HOME/.ruby
export PATH=$PATH:$GEM_HOME/bin

# path for rust if it's lazily installed
export PATH=$PATH:$HOME/.cargo/bin

# path for python if it's lazily installed
export PATH=$PATH:$HOME/.local/bin

# path for yarn if it's lazily installed
export PATH=$PATH:$HOME/.yarn/bin

# path for java
export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
export PATH=$PATH:$LOCAL/apache-maven-3.6.0/bin

# paths
export PATH=$PATH:$HOME/devel/devenv/lazybin
