# oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="enormous"
plugins=(git docker tig golang kubectl)
source $ZSH/oh-my-zsh.sh

# aliases
alias renv="eval \$(tmux show-env -s | grep '^SSH_')"

# pull pr alias
function gfpr() {
  local prnum="$1"
  local refspec="pull/$prnum/head:pr$prnum"
  if git config remote.upstream.url; then
    git fetch upstream "$refspec"
  else
    git fetch origin "$refspec"
  fi
}

# go aliases
for dir in $LOCAL_BIN/go/*;
do
  local v=${dir##*/}
  alias "go$v"="$LOCAL_BIN/go/$v/bin/go"
done

# load fzf
source /usr/share/doc/fzf/examples/key-bindings.zsh

# make c-p/c-n work exactly like up/down arrows
bindkey "^P" up-line-or-search
bindkey "^N" down-line-or-search

# free up the c-q shortcut for use in vim
stty start undef
