FROM leighmcculloch/devenv

# go
RUN curl https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz | tar xz -C /usr/local

# go - env vars
ENV GOPATH_TOOLS="/usr/local/gopath"
ENV GOPATH_USER="$HOME/go"
ENV PATH="${PATH}:$GOPATH_USER/bin:$GOPATH_TOOLS/bin:/usr/local/go/bin"

# go - tools
ENV GOPATH=$GOPATH_TOOLS
RUN go get github.com/nsf/gocode
RUN go get github.com/alecthomas/gometalinter
RUN go get golang.org/x/tools/cmd/goimports
RUN go get golang.org/x/tools/cmd/guru
RUN go get golang.org/x/tools/cmd/gorename
RUN go get github.com/golang/lint/golint
RUN go get github.com/rogpeppe/godef
RUN go get github.com/kisielk/errcheck
RUN go get github.com/jstemmer/gotags
RUN go get github.com/klauspost/asmfmt/cmd/asmfmt
RUN go get github.com/fatih/motion
RUN go get github.com/zmb3/gogetdoc
RUN go get github.com/josharian/impl
RUN go get github.com/mailgun/godebug
RUN go get github.com/kardianos/govendor
RUN go get github.com/tools/godep
RUN go get github.com/derekparker/delve/cmd/dlv
RUN go get golang.org/x/review/git-codereview
RUN go get golang.org/x/tools/cmd/go-contrib-init
RUN go get golang.org/x/tools/cmd/present
RUN go get github.com/jmhodges/justrun

# go - working dir
ENV GOPATH=$GOPATH_USER
RUN mkdir -p $GOPATH/src/github.com/leighmcculloch
RUN mkdir -p $GOPATH/src/4d63.com
