FROM leighmcculloch/devenv

# go
RUN curl https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz | tar xz -C /usr/local

# go - env vars
ENV GOPATH_TOOLS="/usr/local/gopath"
ENV GOPATH_USER="$HOME/go"
ENV PATH="${PATH}:$GOPATH_USER/bin:$GOPATH_TOOLS/bin:/usr/local/go/bin"

# go - tools
ENV GOPATH=$GOPATH_TOOLS
RUN go get github.com/nsf/gocode \
  && go get github.com/golang/dep/cmd/dep \
  && go get github.com/alecthomas/gometalinter \
  && go get golang.org/x/tools/cmd/goimports \
  && go get golang.org/x/tools/cmd/guru \
  && go get golang.org/x/tools/cmd/gorename \
  && go get github.com/golang/lint/golint \
  && go get github.com/rogpeppe/godef \
  && go get github.com/kisielk/errcheck \
  && go get github.com/jstemmer/gotags \
  && go get github.com/klauspost/asmfmt/cmd/asmfmt \
  && go get github.com/fatih/motion \
  && go get github.com/zmb3/gogetdoc \
  && go get github.com/josharian/impl \
  && go get github.com/mailgun/godebug \
  && go get github.com/derekparker/delve/cmd/dlv \
  && go get golang.org/x/review/git-codereview \
  && go get golang.org/x/tools/cmd/go-contrib-init \
  && go get golang.org/x/tools/cmd/present \
  && go get github.com/jmhodges/justrun \
  && go get github.com/golang/protobuf/protoc-gen-go

# go - working dir
ENV GOPATH=$GOPATH_USER
RUN mkdir -p $GOPATH/src/github.com/leighmcculloch
RUN mkdir -p $GOPATH/src/4d63.com

# old app engine go sdk
RUN curl -O https://storage.googleapis.com/appengine-sdks/featured/go_appengine_sdk_linux_amd64-1.9.61.zip \
  && unzip go_appengine_sdk_linux_amd64-1.9.61.zip -d /usr/local/google-appengine-sdk-go/ \
  && rm go_appengine_sdk_linux_amd64-1.9.61.zip
ENV PATH="${PATH}:/usr/local/google-appengine-sdk-go/go_appengine"
