FROM leighmcculloch/devenv

# dartlang
RUN curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
RUN curl https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list
RUN apt-get update
RUN apt-get install dart

ENV PATH="${PATH}:/usr/lib/dart/bin/:${HOME}/.pub-cache/bin/"
