# oh-my-zsh
export ZSH=$HOME/.oh-my-zsh
ZSH_THEME="tiny"
plugins=(git)
source $ZSH/oh-my-zsh.sh

# enable direnv
eval "$(direnv hook zsh)"

# aliases
alias sshenv="eval \$(tmux show-env -s | grep '^SSH_')"
