#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

version=$(cat "$(dirname "$(readlink -f "$0")")/../versions/postgres")
name=${1:-postgres}
network=${2:-container:$(hostname)}

docker run -d --rm -it --network=$network --name=$name \
  -e POSTGRES_USER=$USER \
  -e POSTGRES_PASSWORD= \
  -e POSTGRES_HOST_AUTH_METHOD=trust \
  -e POSTGRES_DATABASE=postgres \
  postgres:$version
