#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

if [ "$#" -eq 0 ]; then
  echo "Current port mappings:"
  echo
  ps -o command= -C socat || true
  echo
fi

if [ "$#" -ne 2 ]; then
  echo "Create new port mappings with:"
  echo
  echo "$(basename $0) <localhost-port> <destination-host>:<destination-port>"
  exit 1
fi

echo "Mapping localhost:$1 to $2..."
socat TCP-LISTEN:$1,fork TCP:$2 &
disown
