#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/pg_ctlcluster ] ; then
  echo -e "\e[1;32mInstalling '$me'...\e[0m"

  sudo apt-get -y install postgresql
  sudo -u postgres sed -Ei 's$(host +all +all +127\.0\.0\.1/32 +)md5$\1trust$' /etc/postgresql/11/main/pg_hba.conf
  sudo -u postgres pg_ctlcluster 11 main start
  sudo -u postgres createuser -dlrs $USER

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi
