#! /usr/bin/env zsh

function title {
  print -P "%F{green}$1%f"
}

# Collect user info
title 'Collecting user info...'
name=$(git config --global user.name)
email=$(git config --global user.email)
signingkey=""
vared -p 'Name: ' -c name
vared -p 'Email: ' -c email
vared -p 'Signing Key (Keyid): ' -c signingkey

# Configure user
title 'Configuring git...'
git config -f "$HOME/.gitconfig.local" user.name "$name"
git config -f "$HOME/.gitconfig.local" user.email "$email"
git config -f "$HOME/.gitconfig.local" user.signingkey "$signingkey!"
git config -f "$HOME/.gitconfig.local" commit.gpgsign true

# Import known GPG keys from GitHub
title 'Importing known gpg keys...'
curl -sSL https://github.com/"$USER".gpg | gpg --import
curl -sSL https://github.com/web-flow.gpg | gpg --import
