#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/az ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  apt-get -y install lsb-release
  echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/azure-cli.list
  apt-key adv --keyserver packages.microsoft.com --recv-keys 52E16F86FEE04B979B07E28DB02C46DF417A0893
  curl -L https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
  apt-get update
  apt-get -y install apt-transport-https azure-cli

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" $@
