#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/bat ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  tmpdir=$(mktemp -d)

  version=0.12.1
  curl -sSL -o "$tmpdir/bat.deb" "https://github.com/sharkdp/bat/releases/download/v${version}/bat_${version}_amd64.deb"
  sudo apt-get -y install -f "${tmpdir}/bat.deb"

  rm -fr "$tmpdir"

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
