#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/bazel ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
  echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list

  sudo apt-get update
  sudo apt-get -y install bazel bazel-3.2.0

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
