#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -d /home/linuxbrew ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
