#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/cf ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list \
  curl https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
  sudo apt-get update
  sudo apt-get -y install cf-cli

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
