#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/clone ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  version=2.0.1
  curl -sSL https://github.com/leighmcculloch/clone/releases/download/v${version}/clone_${version}_linux_amd64.tar.gz | tar xz -C $LOCAL
  ln -sf $LOCAL/clone_${version}_linux_amd64/clone $LOCAL_BIN/clone

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
