#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/bin/crystal ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sL "https://keybase.io/crystal/pgp_keys.asc" | sudo apt-key add -
  echo "deb https://dist.crystal-lang.org/apt crystal main" | sudo tee /etc/apt/sources.list.d/crystal.list
  sudo apt-get update
  sudo apt-get install -y \
    crystal \
    libssl-dev \
    libxml2-dev \
    libyaml-dev \
    libgmp-dev \
    libreadline-dev \
    libz-dev

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
