#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/deno ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  version=1.0.0
  curl -sSL -o /tmp/deno-x86_64-unknown-linux-gnu.zip https://github.com/denoland/deno/releases/download/v${version}/deno-x86_64-unknown-linux-gnu.zip
  unzip /tmp/deno-x86_64-unknown-linux-gnu.zip -d $LOCAL_BIN
  rm /tmp/deno-x86_64-unknown-linux-gnu.zip

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
