#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f "$LOCAL_BIN/docker-compose" ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -L "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-$(uname -s)-$(uname -m)" -o "$LOCAL_BIN/docker-compose"
  chmod +x "$LOCAL_BIN/docker-compose"

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
