#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -d "$HOME/.dotnet" ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  ## install sdks for common versions
  dir=$(mktemp -d)
  pushd $dir
  curl -sSLO https://dot.net/v1/dotnet-install.sh
  chmod +x dotnet-install.sh
  ./dotnet-install.sh -c Current
  ./dotnet-install.sh -c 5.0
  ./dotnet-install.sh -c 3.1
  ./dotnet-install.sh -c 2.1
  popd
  rm -fr $dir

  # install official tool for formatting
  dotnet tool install -g dotnet-format

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
