#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f /usr/local/bin/firebase ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  yarn global add firebase-tools

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
