#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/firebase ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -Lo $LOCAL_BIN/firebase https://firebase.tools/bin/linux/latest
  chmod +x $LOCAL_BIN/firebase

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
