#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $HOME/.local/bin/aws ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/google-cloud-sdk-182.0.0-linux-x86_64.tar.gz | tar xz -C /usr/local
  /usr/local/google-cloud-sdk/install.sh \
    --usage-reporting false \
    --additional-components app-engine-go cloud-datastore-emulator pubsub-emulator \
    --quiet
  ln -sf /usr/local/google-cloud-sdk/bin/gcloud /usr/local/bin/gcloud

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" $@
