#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/githubclone ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  version=1.5.0
  curl -sSL https://github.com/leighmcculloch/githubclone/releases/download/v${version}/githubclone_${version}_linux_amd64.tar.gz | tar xz -C $LOCAL
  ln -sf $LOCAL/githubclone_${version}_linux_amd64/githubclone $LOCAL_BIN/githubclone

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
