#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/githubcloneall ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sSL https://github.com/leighmcculloch/githubcloneall/releases/download/v1.0.1/githubcloneall_1.0.1_linux_x64.tar.gz | tar xz -C $LOCAL
  ln -sf $LOCAL/githubcloneall_1.0.1_linux_x64/githubcloneall $LOCAL_BIN/githubcloneall

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
