#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"
installdir="$LOCAL_BIN/go"

versions=(
  "1.13beta1"
  "1.12.8"
  "1.11.13"
)

{
  if ! [ -d "$installdir" ] ; then
    echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

    sudo rm -fr "$installdir"

    for v in "${versions[@]}"
    do
      echo -e "\e[1;93mInstalling 'go$v'...\e[0m"
      mkdir -p "$installdir/$v"
      curl "https://dl.google.com/go/go$v.linux-amd64.tar.gz" | tar xz --strip-components=1 -C "$installdir/$v"
    done

    echo -e "\e[1;32mFinished installing '$me'.\e[0m"
  fi
} 1>&2

go "$@"
