#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/"$me" ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  go get github.com/golang/lint/golint

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" $@
