#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/goreleaser ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sSL https://github.com/goreleaser/goreleaser/releases/download/v0.117.2/goreleaser_Linux_x86_64.tar.gz | tar xz -C $LOCAL_BIN goreleaser

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
