#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/gotestsum ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sSL https://github.com/gotestyourself/gotestsum/releases/download/v0.3.5/gotestsum_0.3.5_linux_amd64.tar.gz | tar xz -C $LOCAL_BIN gotestsum

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
