#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/gs ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sSL https://github.com/leighmcculloch/gs/releases/download/v1.0.0/gs_1.0.0_linux_amd64.tar.gz | tar xz -C $LOCAL
  ln -sf $LOCAL/gs_1.0.0_linux_amd64/gs $LOCAL_BIN/gs

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" $@
