#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/hub ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sSL https://github.com/github/hub/releases/download/v2.6.0/hub-linux-amd64-2.6.0.tgz | tar xz -C $LOCAL
  ln -sf $LOCAL/hub-linux-amd64-2.6.0/bin/hub $LOCAL_BIN/hub

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" $@
