#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/hugo ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sSL https://github.com/gohugoio/hugo/releases/download/v0.53/hugo_0.53_Linux-64bit.tar.gz | tar xz -C $LOCAL_BIN hugo

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
