#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $HOME/.cargo/bin/"$me" ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl https://sh.rustup.rs -sSf | sh -s -- -y

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" $@
