#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $HOME/.rvm/bin/rvm ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  sudo apt-get install -y gnupg
  curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -
  curl -sSL https://get.rvm.io | bash -s stable

  version=2.6.3
  date=20191130
  rvm mount -r "https://github.com/leighmcculloch/devenv_compile_ruby/releases/download/v${version}-${date}/ruby-${version}.tar.bz2" --verify-downloads 2

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
