#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $HOME/.rvm/bin/rvm ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  sudo apt-get install -y gnupg
  gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
  curl -sSL https://get.rvm.io | bash -s stable

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
