#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/serve ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  dir=$(mktemp -d)
  pushd $dir
  go mod init tool
  go get -u 4d63.com/serve
  popd
  rm -fr $dir

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
