#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/swift ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  sudo apt-get -y install \
    binutils \
    git \
    libc6-dev \
    libcurl4 \
    libedit2 \
    libpython2.7 \
    libsqlite3-0 \
    libxml2 \
    pkg-config \
    tzdata \
    zlib1g-dev \
    libtinfo5 \
    libncurses5

  curl -L https://swift.org/builds/swift-5.2.4-release/ubuntu1804/swift-5.2.4-RELEASE/swift-5.2.4-RELEASE-ubuntu18.04.tar.gz | tar xz -C $LOCAL
  ln -sf $LOCAL/swift-5.2.4-RELEASE-ubuntu18.04/usr/bin/swift $LOCAL_BIN/swift

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
