#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/swift ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  sudo apt-get -y install clang libtinfo5 libpython2.7 libncurses5 libncurses5 libxml2

  curl -L https://swift.org/builds/swift-4.2.1-release/ubuntu1804/swift-4.2.1-RELEASE/swift-4.2.1-RELEASE-ubuntu18.04.tar.gz | tar xz -C $LOCAL
  ln -sf $LOCAL/swift-4.2.1-RELEASE-ubuntu18.04/usr/bin/swift $LOCAL_BIN/swift

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" $@
