#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/v ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  version=0.1.29
  curl -sSL -o /tmp/v_linux.zip https://github.com/vlang/v/releases/download/$version/v_linux.zip
  unzip /tmp/v_linux.zip -d $LOCAL
  rm /tmp/v_linux.zip
  ln -sf $LOCAL/v/v $LOCAL_BIN/v

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
