#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -d $LOCAL_BIN/"$me" ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  vim_commit=197c6b7
  compile_commit=22a89a5
  curl -sSL "https://dl.bintray.com/leighmcculloch/vim_compile/vim_${vim_commit}_${compile_commit}.tar.gz" | tar xz -C $LOCAL

  deps=$(apt-cache depends vim-nox | awk '/Depends: lib/{print$2}')
  sudo apt-get install -y $deps

  git clone https://github.com/leighmcculloch/vim_dotfiles $DEVEL/.vim_dotfiles
  pushd $DEVEL/.vim_dotfiles
  git remote set-url --add --push origin github:leighmcculloch/vim_dotfiles
  make install
  popd

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
