#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/zig ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  version=0.7.0
  curl -sSL https://ziglang.org/download/$version/zig-linux-x86_64-$version.tar.xz | tar xJ -C $LOCAL
  ln -sf $LOCAL/zig-linux-x86_64-$version/zig $LOCAL_BIN/zig

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
