#!/usr/bin/env bash

set -o errexit
set -o pipefail
set -o nounset

me="$(basename "$0")"

if ! [ -f $LOCAL_BIN/zig ] ; then
  echo -e "\e[1;32mInstalling '$me' on first use...\e[0m"

  curl -sSL https://ziglang.org/download/0.6.0/zig-linux-x86_64-0.6.0.tar.xz | tar xJ -C $LOCAL
  ln -sf $LOCAL/zig-linux-x86_64-0.6.0/zig $LOCAL_BIN/zig

  echo -e "\e[1;32mFinished installing '$me'.\e[0m"
fi

"$me" "$@"
